# Generated by Django 4.0.2 on 2022-02-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(null=True)),
                ('numOfPage', models.IntegerField(null=True)),
                ('author', models.TextField(null=True)),
                ('image_path', models.TextField(null=True)),
                ('publisher', models.TextField(null=True)),
                ('numInStore', models.IntegerField(null=True)),
                ('unitPrice', models.IntegerField(null=True)),
            ],
        ),
    ]
