# Generated by Django 4.0.3 on 2022-03-04 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.TextField(null=True)),
                ('role', models.TextField(null=True)),
                ('salary', models.FloatField(null=True)),
                ('gender', models.TextField(null=True)),
                ('dateOfBirth', models.TextField(null=True)),
                ('ussername', models.TextField(null=True)),
                ('password', models.TextField(null=True)),
                ('fullname', models.TextField(null=True)),
                ('lastname', models.TextField(null=True)),
                ('firstname', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='numInStore',
        ),
        migrations.RemoveField(
            model_name='book',
            name='unitPrice',
        ),
        migrations.AddField(
            model_name='book',
            name='categorical',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.TextField(null=True)),
                ('price', models.FloatField(null=True)),
                ('discount', models.FloatField(null=True)),
                ('bookID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='test_app.book')),
                ('employeeID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='test_app.employee')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='employeeID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='test_app.employee'),
        ),
    ]
